// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLRvvyUuzxAHjCpCgNF6jakw0mKubCclM',
    appId: '1:982802152666:web:b44ed75f6fc339b12779e3',
    messagingSenderId: '982802152666',
    projectId: 'componentes5c-efe70',
    authDomain: 'componentes5c-efe70.firebaseapp.com',
    storageBucket: 'componentes5c-efe70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW9E0YqPXVWFTiMUXdICD-gpplSiH4Zzo',
    appId: '1:982802152666:android:08c1fcd612be098b2779e3',
    messagingSenderId: '982802152666',
    projectId: 'componentes5c-efe70',
    storageBucket: 'componentes5c-efe70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDiPxwi4fU7QApgWRwRIjISmfG6Aburv0',
    appId: '1:982802152666:ios:d7350e5f792e063d2779e3',
    messagingSenderId: '982802152666',
    projectId: 'componentes5c-efe70',
    storageBucket: 'componentes5c-efe70.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
